[package]
name = "xdg-demo"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = "1.0.95"
ashpd = "0.10.2"
futures-util = "0.3.31"
tokio = { version = "1.19.2", features = ["macros", "net", "rt", "sync"] }
url = "2.5.4"
zbus = "5.5.0"
